# Header
menu:
  Home:
    path: /
    icon: images/open_03.png
  About:
    path: /about/
    icon: images/open_05.png
  Downloads:
    path: /downloads/
    icon: images/open_02.png
  News:
    path: /news/
    icon: images/open_01.png
  FAQ:
    path: /faq/
    icon: images/open_04.png

# Miscellaneous
favicon: /favicon.png
google_analytics:
twitter:
